const TRANSLATION = {
  en: {
    global: {
      cookies: {
        title: "Cookies",
        description:
          "This website uses cookies to ensure you get the best experience. Information about language and theme preferences are stored in cookies.",
        buttons: {
          accept: "Accept cookies",
          acceptNecessary: "Accept necessary only",
          decline: "Decline all cookies",
        },
      },
      contact: {
        btnTxt: "Contact me",
        dialog: {
          title: "Contact me",
          subtitle: "Get in contact through your preferred social channel!",
          closeBtn: "Close",
        },
      },
      footer: {
        updated: "updated lastly",
        favicon: "favicon by Freepik",
      },
      navbar: {
        shortcuts: ["Home", "About", "Skills", "Projects", "Experience"],
      },
      projectPanel: {
        flagShip: "FLAGSHIP",
        newProject: "NEW",
      },
      theme: {
        light: "Light",
        dark: "Dark",
        system: "System",
      },
    },
    index: {
      aboutme: {
        title: "ABOUT ME",
        subtitle: "Enthusiastic problem-solver dedicated to web development",
      },
      experience: {
        title: "EXPERIENCE",
        header: "Quick summary of my most recent experiences",
        present: "Present",
      },
      newproject: {
        title: "CONTACT",
        hero: {
          title: "Get started!",
          subtitle: "Got a project in mind? Let's chat.",
        },
      },
      projects: {
        title: "PROJECTS",
        header: "Things I've built so far",
        moreBtn: {
          btnText: "and more...",
        },
      },
      skills: {
        title: "SKILLS",
        headers: {
          skills: "Technologies and tools I am good with",
          learning: "Additionally I'm currently learning",
        },
        listBtn: {
          showMore: "SHOW MORE",
          showLess: "SHOW LESS",
        },
        imgCredits: "Logos and images are generated by shields.io",
      },
      title: {
        header: {
          hello: "Hello, I'm",
          subtitle:
            "a passionate computer science student dedicated to mastering cutting-edge technologies and shaping the future as a skilled problem-solver and worker of the digital age.",
        },
        messageBtn: {
          btnTxt: "Send me a message",
          dialog: {
            title: "Send me a message",
            subtitle: "You reach me best via Telegram.",
            closeBtn: "Close",
          },
        },
        video: {
          overlays: {
            responsive: "RESPONSIVE",
            modern: "MODERN",
          },
          credits: "video by u_vt453kmgmm from Pixabay",
        },
      },
    },
    projects: {
      header: {
        title: "Projects",
        subtitle: "Curated catalogue of my recent work.",
      },
      footer: {
        title:
          "Find even more projects and the source code for this portfolio website on my GitHub!",
        btnText: "Check my GitHub",
      },
      newProject: {
        new: "NEW",
        dialog: {
          title: "New project in mind?",
          subtitle: "Get in contact and let's discuss how to proceed.",
          closeBtn: "Close",
        },
      },
    },
    project: {
      header: {
        backToProjectsBtn: {
          btnText: "Back to list",
        },
        sourceCodeBtn: {
          btnText: "View source code on GitHub",
          private: "Source code is private",
        },
      },
      demoLink: {
        btnText: "Check the live project on web",
        explotrack: "Check the demo project on web",
        deployedOn: "Deployed on",
      },
      video: {
        notWorking: {
          title: "Video not working?",
          btnText: "Open the video in Dropbox",
        },
        smallScreen: {
          title: "You are viewing this video on a really small screen!",
          subtitle:
            "If possible, I'd suggest switching to landscape mode for a better view.",
        },
      },
      description: {
        title: "Description",
      },
      learnMore: {
        private: {
          header: "Unfortunately the source code is private.",
          subtitle:
            "I'll still be happy to answer any questions you might have!",
          btnText: "Contact me fore more info",
        },
        public: {
          header: "Want to learn more about this project?",
          subtitle:
            "Check the source code and read the full documentation on GitHub!",
          btnText: "Check the GitHub repo",
        },
      },
      navbar: {
        title: "Check other projects as well!",
      },
    },
  },
};

export default TRANSLATION;
